apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: poc-camunda-api
build:
  #local:
  #  useBuildkit: true             # We use BuildKit
  artifacts:
  - image: poc-camunda-api
    context: api
    docker:
      dockerfile: Dockerfile
      #target: debug               # deploy the debug image
deploy:
  helm:
    releases:
    - name: app
      chartPath: ../deploy/helm/poc-camunda-api
      namespace: camunda
      createNamespace: true
      #port: 5138
